// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqamdpufgofyyuaaetxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYW1kcHVmZ29meXl1YWFldHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTc5NjIsImV4cCI6MjA3MjY3Mzk2Mn0.oQD64DBtsgMJkf2wW4Pdzk5u9Ux6-g8uULsXxYXYnjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});